package net.digitalid.utility.generator.interceptors;

/**
 * Description.
 */
public class InterceptorTest {
    
    // Test interceptors on methods with and without return types and in the former case also generics.
    
    // Also test that the implementation of abstract methods can be generated by interceptors (with a test annotation like @GenerateImplementation?).
    
}
